Repository zycamichaela/Hacktoberfest-2022, pull requests merged in 2020-10, with the labels that each got.

#7 Kankuu
  Dockerfile
Labels: enhancement

#6 sumbang hacktoberfest
  CONTRIBUTORS.md
  profiles/heru_hermawan.md
  scripts/hello_world_by_iamheru.php
Labels: good first issue

#17 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/saipul.md
  scripts/hello_world_saifoelloh.go
Labels: hacktoberfest-accepted

#13 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/aryarfani.md
  scripts/hello_world_ary.dart
Labels: hacktoberfest-accepted

#18 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/farrasrayhand.md
  scripts/hello_world_farrasrayhand.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#20 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/divetri.md
  scripts/hello_world_divetri.ino
Labels: hacktoberfest

#21 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/leoprananta.md
  scripts/hello_world_leoprananta.js
Labels: hacktoberfest, hacktoberfest-accepted

#40 "add it hacktoberfest"
  profiles/zhana.md
  scripts/hello_world_zhana.cpp
Labels: hacktoberfest-accepted

#22 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/ilham.md
  scripts/hello_world_ilham.sh
Labels: hacktoberfest, hacktoberfest-accepted

#23 Add it to "Hacktoberfest"
  CONTRIBUTORS.md
  profiles/adi_purnomo.md
  scripts/Hello_World.rb
Labels: hacktoberfest, hacktoberfest-accepted

#24 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/arisandi.md
  scripts/hello_world_arisandi.java
Labels: hacktoberfest, hacktoberfest-accepted

#25 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/FebrianS_Putra.md
  scripts/Hello_world_Febriansputra.js
Labels: hacktoberfest, hacktoberfest-accepted

#27 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/Wahyu.md
  scripts/hello_world_Wahyu.rb
Labels: hacktoberfest

#30 menambahkan script python
  CONTRIBUTORS.md
  profiles/fahmiady.md
  scripts/Hello_word_fahmiady11.py
Labels: hacktoberfest, hacktoberfest-accepted

#31 add empalgentong
  CONTRIBUTORS.md
  profiles/empalgentong.md
  scripts/hello_world_empalgentong.sh
Labels: hacktoberfest-accepted

#32 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/jeffrywu28.md
  scripts/hello_world_jeff.pl
Labels: hacktoberfest-accepted

#33 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/akhid.md
  scripts/hello_world_yanuarakhid.sh
Labels: hacktoberfest-accepted

#42 Hacktoberfest 🎉
  CONTRIBUTORS.md
  profiles/rndprdn.md
  scripts/hello_world.rb
Labels: hacktoberfest-accepted

#43 Add it "hacktoberfest"
  CONTRIBUTORS.md
  profiles/rcmiryad123.md
  scripts/hello_world_rcmiryad123.js
Labels: hacktoberfest-accepted
